// Get welcoming message
GET http://localhost:3000/

###

// Initiate a new customer registry
POST http://localhost:3000/v1/customers
// type could be business or consumer, to differentiate the B2B2B from B2B2C
// entity needs to be discussed

{
    "kind": "business",
    "entity": "Anchorage hold"
}

###

// Update the customers' kyc information
PUT http://localhost:3000/v1/customers/878bc7da-4809-11ed-b878-0242ac120002

{
    "kyc_version": 1,
    "kyc": [
        { "question_id": "external_id_question_1", "answer": "some answer" },
        { "question_id": "external_id_question_3", "answer": ["a", "b"] }
    ]
}

###

// Update the customers' kyc information, version of tuples
PUT http://localhost:3000/v2/customers/878bc7da-4809-11ed-b878-0242ac120002

{
    "kyc_version": 1,
    "kyc": [
        "external_id_question_1:some answer 2",
        "external_id_question_2:true",
        "external_id_question_3:1,2,3"
    ]
}

###

// Get the customers' kyc information
GET http://localhost:3000/v1/customers/878bc7da-4809-11ed-b878-0242ac120002

###

// Submit the customer info
POST http://localhost:3000/v1/customers/878bc7da-4809-11ed-b878-0242ac120002/submit